### ISSUE TITLE
feat(cloud-native): add attribute for SQL database schema in Helm chart

### ISSUE THREAD

**Issue by iromli** [GluuFederation/gluu4#94]
Current Helm chart's `values.yaml` doesn't have attribute to store SQL database schema.
In postgres-based setup, users may want to use custom schema and avoid `public` schema.

```
config:
  configmap:
    # -- SQL database dialect. `mysql` or `pgsql`
    cnSqlDbDialect: mysql
    # -- SQL database host uri.
    cnSqlDbHost: my-release-mysql.default.svc.cluster.local
    # -- SQL database port.
    cnSqlDbPort: 3306
    # -- SQL database name.
    cnSqlDbName: gluu
    # -- SQL database username.
    cnSqlDbUser: gluu
    # -- SQL database timezone.
    cnSqlDbTimezone: UTC
    # -- SQL password file holding password from config.configmap.cnSqldbUserPassword .
    cnSqlPasswordFile: /etc/gluu/conf/sql_password
    # -- SQL password  injected as config.configmap.cnSqlPasswordFile .
    cnSqldbUserPassword: Test1234#
```

Current workaround is to add `GLUU_SQL_DB_SCHEMA` to `global.userEnvs.normal`.

Note that the underlying `pygluu.containerlib` library sets `GLUU_SQL_DB_SCHEMA=""` as default.
